# -*- coding: utf-8 -*-
"""Hackathon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VTaMhje1fGJ_QmDf7C0jGjjEoYwaBrui
"""

import pandas as pd
import matplotlib.pyplot as plt
import io

from google.colab import files
uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded['business_data.csv']))

"""#Stocks Holdings

"""

line, = plt.plot(df.iloc[:,0], df.iloc[:,1])
line.set_color("red")
plt.xlabel('Year')
plt.ylabel('Value of stocks holding that year')
plt.title('Plot of Stocks holding in the recent FYs')
plt.show()

"""#Short Term Investment"""

plt.plot(df.iloc[:,0], df.iloc[:,2])
plt.xlabel('Year')
plt.ylabel('Value of net short term investments')
plt.title('Plot of Short Term Investments')
plt.show()

"""#Long Term Investment"""

line, = plt.plot(df.iloc[:,0], df.iloc[:,3])
line.set_color("green")
plt.xlabel('Year')
plt.ylabel('Value of net long term investments')
plt.title('Plot of Long Term Investments')
plt.show()

"""#Profits"""

line, = plt.plot(df.iloc[:,0], df.iloc[:,4])
line.set_color("Indigo")
plt.xlabel('Year')
plt.ylabel('Profit')
plt.title('Plot of Profits in the recent FYs')
plt.show()

"""#Property Holding Value"""

line, = plt.plot(df.iloc[:,0], df.iloc[:,5])
line.set_color("red")
plt.xlabel('Year')
plt.ylabel('Property Holding Value')
plt.title('Plot of Property holding in the recent FYs')
plt.show()

"""#Loan Taken"""

plt.plot(df.iloc[:,0], df.iloc[:,6])
plt.xlabel('Year')
plt.ylabel('Value of loan taken')
plt.title('Plot of Loan')
plt.show()

"""#Expenditure"""

line, = plt.plot(df.iloc[:,0], df.iloc[:,7])
line.set_color("green")
plt.xlabel('Year')
plt.ylabel('Expenditure')
plt.title('Expenditure in the recent FYs')
plt.show()

"""#Tax Paid"""

line, = plt.plot(df.iloc[:,0], df.iloc[:,8])
line.set_color("indigo")
plt.xlabel('Year')
plt.ylabel('Tax Paid')
plt.title('Plot of Tax Paid in the recent FYs')
plt.show()

"""#Living Expenses"""

line, = plt.plot(df.iloc[:,0], df.iloc[:,9])
line.set_color("green")
plt.xlabel('Year')
plt.ylabel('Living Expenses')
plt.title('Plot of Daily Living Expenses')
plt.show()

"""#Assets"""

#For Assets
x = df.iloc[:,0]

plt.plot(x, df.iloc[:,1], label="Stocks")
plt.plot(x, df.iloc[:,2], label="STI")
plt.plot(x, df.iloc[:,3], label="LTI")
plt.plot(x, df.iloc[:,4], label="Profit")
plt.plot(x, df.iloc[:,5], label="Property")


plt.xlabel('Financial Year')
plt.ylabel('Assets')
plt.title('Plot of all assets in the recent FYs')
plt.legend()
plt.show()

"""#Liabilities"""

#For Liabilities
x = df.iloc[:,0]

plt.plot(x, df.iloc[:,6], label="Loan")
plt.plot(x, df.iloc[:,7], label="Expenditure")
plt.plot(x, df.iloc[:,8], label="Tax-Paid")
plt.plot(x, df.iloc[:,9], label="Daily-Living-Expenses")


plt.xlabel('Financial Year')
plt.ylabel('Liabilities')
plt.title('Plot of all liabilities in the recent FYs')
plt.legend()
plt.show()

"""#Assets and Liabilities"""

df['Total Investments'] = df.iloc[:,1] + df.iloc[:,2] + df.iloc[:,3] + df.iloc[:,4] + df.iloc[:,5]
df['Total Liability'] = df.iloc[:,6] + df.iloc[:,7] + df.iloc[:,8] + df.iloc[:,9]
plt.plot(x, df.iloc[:,10], label="Total-Investments")
plt.plot(x, df.iloc[:,11], label="Total-Liablities")
plt.xlabel("Financial Year")
plt.ylabel("Assets and Liabilities")
plt.title("Plot of assets and liablities in the recent FYs")
plt.legend()
plt.show()

"""#Net Worth"""

df['Net-Worth'] = df.iloc[:,10] - df.iloc[:,11]
line, = plt.plot(x, df.iloc[:,12], label="Net-Worth")
line.set_color("red")
plt.xlabel("Financial Year")
plt.ylabel("Net Worth")
plt.title("Plot of net worth in the recent FYs")
plt.legend()
plt.show()